swagger: '2.0'
info:
  description: This is the API of the group PlaceHolder
  version: 1.0.0
  title: PlaceHolder API
  # put the contact info for your development or API team
  contact:
    email: ivansd.99@gmail.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: projects
  description: projects data
paths:
  /projects:
    get:
      tags:
      - projects
      summary: Get all projects
      operationId: getAll
      produces:
      - application/json
      responses:
        200:
          description: sucessful operation
          schema:
            $ref: '#/definitions/Project'
        default:
          description: unexpected error
    post:
      tags:
      - projects
      summary: Adds a project
      operationId: addProject
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: projectName
        in: path
        description: Project to add
        required: true
        type: string
      responses:
        201:
          description: project created
        400:
          description: bad request
        409:
          description: an existing project already exists
  /projects/{projectId}:
    get:
      tags:
      - projects
      summary: Gets a project by id
      operationId: getProject
      parameters:
      - name: projectId
        in: path
        description: ID of project to return
        required: true
        type: string
      responses:
        200:
          description: sucessful operation
          schema:
            $ref: '#/definitions/Project'
        400:
          description: Invalid ID supplied
        404:
          description: Project not found
    delete:
      tags:
      - projects
      summary: Deletes a project
      operationId: deleteProject
      parameters:
      - name: projectId
        in: path
        description: Project id to delete
        required: true
        type: string
      responses:
        204:
          description: No content
        400:
          description: Invalid ID supplied
        404:
          description: Project not found
    put:
      tags:
      - projects
      summary: Updates a project
      operationId: updateProject
      produces:
      - application/json
      parameters:
      - name: projectId
        in: path
        description: Project id to update
        required: true
        type: string
      responses:
        204:
          description: No content
        400:
          description: Invalid ID supplied
        404:
          description: Project not found
definitions:
  Project:
    type: object
    required:
    - id
    - name
    - tasks
    properties:
      id:
        type: string
        example: 'p1'
      name:
        type: string
        example: 'Cosas de casa'
      tasks:
        type: array
        items:
          $ref: '#/definitions/Task'
  Task:
    type: object
    required:
    - id
    - name
    properties:
      id:
        type: string
        example: 't1'
      name:
        type: string
        example: 'Sacar la basura'
# Added by API Auto Mocking Plugin
# host: placeholder-aiss.appspot.com
# basePath: /api
schemes:
 - https
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /placeholder-aiss/placeholder-api-aiss/1.0.0