swagger: '2.0'
info:
  description: This is the API of the group PlaceHolder
  version: 1.0.0
  title: PlaceHolder API
  # put the contact info for your development or API team
  contact:
    email: ivansd.99@gmail.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: projects
  description: projects data
- name: tasks
  description: tasks data
paths:
  /projects:
    get:
      tags:
      - projects
      summary: Gets all projects
      operationId: getAllProjects
      produces:
      - application/json
      parameters:
      - in: query
        name: firstLetter
        type: string
        description: Filter projects by the first letter
      - in: query
        name: start
        type: integer
        description: Start a page by a position
      - in: query
        name: size
        type: integer
        description: Size of the page
      responses:
        200:
          description: sucessful operation
          schema:
            $ref: '#/definitions/Project'
        default:
          description: unexpected error
    post:
      tags:
      - projects
      summary: Adds a project
      operationId: addProject
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: projectName
        in: path
        description: Project to add
        required: true
        type: string
      responses:
        201:
          description: project created
        400:
          description: bad request
        409:
          description: an existing project already exists
  /projects/{projectId}:
    get:
      tags:
      - projects
      summary: Gets a project by id
      operationId: getProject
      parameters:
      - name: projectId
        in: path
        description: ID of project to return
        required: true
        type: string
      responses:
        200:
          description: sucessful operation
          schema:
            $ref: '#/definitions/Project'
        400:
          description: Invalid ID supplied
        404:
          description: Project not found
    delete:
      tags:
      - projects
      summary: Deletes a project
      operationId: deleteProject
      parameters:
      - name: projectId
        in: path
        description: Project id to delete
        required: true
        type: string
      responses:
        204:
          description: No content
        400:
          description: Invalid ID supplied
        404:
          description: Project not found
    put:
      tags:
      - projects
      summary: Updates a project
      operationId: updateProject
      produces:
      - application/json
      parameters:
      - name: projectId
        in: path
        description: Project id to update
        required: true
        type: string
      responses:
        204:
          description: No content
        400:
          description: Invalid ID supplied
        404:
          description: Project not found
  /projects/{projectId}/{taskId}:
    post:
      tags:
      - projects
      summary: Adds a task into a project
      operationId: addProjectTask
      parameters:
      - name: projectId
        in: path
        description: ID of project
        required: true
        type: string
      - name: taskId
        in: path
        description: Task to add
        required: true
        type: string
      responses:
        200:
          description: sucessful operation
          schema:
            $ref: '#/definitions/Project'
        400:
          description: Task already in the project
        404:
          description: Not found
    delete:
      tags:
      - projects
      summary: Delete a task in a project
      operationId: deleteProjectTask
      parameters:
      - name: projectId
        in: path
        description: ID of project
        required: true
        type: string
      - name: taskId
        in: path
        description: Task to add
        required: true
        type: string
      responses:
        204:
          description: no content
          schema:
            $ref: '#/definitions/Project'
        404:
          description: Not found
  /tasks:
    get:
      tags:
      - tasks
      summary: Gets all tasks
      operationId: getAllTasks
      produces:
      - application/json
      parameters:
      - in: query
        name: firstLetter
        type: string
        description: Filter tasks by the first letter
      - in: query
        name: start
        type: integer
        description: Start a page by a position
      - in: query
        name: size
        type: integer
        description: Size of the page
      responses:
        200:
          description: sucessful operation
          schema:
            $ref: '#/definitions/Task'
        default:
          description: unexpected error
    post:
      tags:
      - tasks
      summary: Adds a task
      operationId: addTask
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: taskName
        in: path
        description: Task to add
        required: true
        type: string
      responses:
        201:
          description: task created
        400:
          description: bad request
        409:
          description: an existing task already exists
  /tasks/{taskId}:
    get:
      tags:
      - tasks
      summary: Gets a task by id
      operationId: getTask
      parameters:
      - name: taskId
        in: path
        description: ID of task to return
        required: true
        type: string
      responses:
        200:
          description: sucessful operation
          schema:
            $ref: '#/definitions/Task'
        400:
          description: Invalid ID supplied
        404:
          description: Task not found
    delete:
      tags:
      - tasks
      summary: Deletes a task
      operationId: deleteTask
      parameters:
      - name: taskId
        in: path
        description: Task id to delete
        required: true
        type: string
      responses:
        204:
          description: No content
        400:
          description: Invalid ID supplied
        404:
          description: Task not found
    put:
      tags:
      - tasks
      summary: Updates a task
      operationId: updateTask
      produces:
      - application/json
      parameters:
      - name: taskId
        in: path
        description: Task id to update
        required: true
        type: string
      responses:
        204:
          description: No content
        400:
          description: Invalid ID supplied
        404:
          description: Task not found
definitions:
  Project:
    type: object
    required:
    - id
    - name
    - tasks
    properties:
      id:
        type: string
        example: 'p1'
      name:
        type: string
        example: 'Cosas de casa'
      tasks:
        type: array
        items:
          $ref: '#/definitions/Task'
  Task:
    type: object
    required:
    - id
    - name
    properties:
      id:
        type: string
        example: 't1'
      name:
        type: string
        example: 'Sacar la basura'
# Added by API Auto Mocking Plugin
# host: placeholder-aiss.appspot.com
# basePath: /api
schemes:
 - https
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /placeholder-aiss/placeholder-api-aiss/1.0.0